baseURL: "https://enriquegallardov.github.io/CAS/"
languageCode: es-co
title: CAS
theme: PaperMod
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  profileMode:
    enabled: true
    title: CAS • 2022-2024
    subtitle: Enrique Gallardo
    buttons:
      - name: Registros
        url: "/CAS/registros/"
      - name: PIP
        url: "/CAS/pip/"
      - name: Github
        url: "https://github.com/enriquegallardov"
  homeInfoParams:
    Title: CAS • 2022-2024
    Content: Enrique Gallardo
menu:
  main:
    - identifier: archive
      name: Archivos
      url: /archivos/
      weight: 10
    - identifier: busqueda
      name: Busqueda
      url: /busqueda/
      weight: 20
