baseURL = 'https://enriquegallardov.github.io/CAS/'
languageCode = 'es-co'
title = 'Bitácora CAS'
theme = 'PaperMod'
[outputs]
home = [ 'HTML', 'RSS', 'JSON' ]
[params.profileMode]
enabled = true
title = "Bitácora CAS • 2022-2024"
subtitle = "Enrique Gallardo"

  [[params.profileMode.buttons]]
  name = "Archivo"
  url = "/CAS/archivo"

  [[params.profileMode.buttons]]
  name = "Registros"
  url = "/CAS/registros"

  [[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/enriquegallardov"

[params.homeInfoParams]
Title = "Bitácora CAS • 2022-2024"
Content = "Enrique Gallardo"


